# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Set up a virtual environment
          command: |
            python3 -m venv venv

      - run:
          name: Install/upgrade flake8 linter
          command: |
            . venv/bin/activate
            pip install --upgrade flake8

      - run:
          name: Run Flake8 on source and test files
          command: |
            . venv/bin/activate
            flake8 ./src ./tests

      - run:
          name: Install/upgrade setup-related packages
          command: |
            . venv/bin/activate
            pip install --upgrade pip setuptools wheel

      - run:
          name: Install the package
          command: |
            . venv/bin/activate
            pip install .

      - run:
          name: Run the unit tests
          command: |
            . venv/bin/activate
            python setup.py test

      - store_artifacts:
          path: htmlcov
          destination: test-reports
